### PR TITLE
Feature/dna translation add start site 230517

### PR DESCRIPTION
**Pull request by KirkD-Glysade**

### CODE REVIEW

**Comment by KirkD-Glysade** [comment]
Should this also be merged since the companion PR from DataFxnPylibTest was merged?  That one contained the tests for this DataFxn modification.

**Comment by jones-gareth** [comment]
> 

Yes, ideally it should now be merged.  However, this then releases the data function for everyone.  Should check with Matt before doing that.

**Comment by KirkD-Glysade** [comment]
I keep forgetting that merging releases it to the world.

**Comment by mattstahl00** [comment]
For pure Python DataFxns (as opposed to C#) I don't see any reason to hold it back from going public.  Go ahead and merge if it's ready for customers to use.

**Pull request merged**
