### PR TITLE
PAINS Filters

### PR DESCRIPTION
**Pull request by DavidACosgrove**
Import of PAINSFilters.yaml.

### CODE REVIEW

**Comment by jones-gareth** [comment]
The bond highlighting is not working for me- at least for the AZ dataset.  This is probably for us to fix not Dave.
image

**Comment by jones-gareth** [comment]
LGTM

**Comment by mattstahl00** [comment]
Please leave cells in the "Smiles PAINS Map" column empty if no filters match

**Review by jones-gareth — APPROVED** [review]
LGTM

**Pull request merged**
