### PR TITLE
Feature/sequence tools 230725

### PR DESCRIPTION
**Pull request by KirkD-Glysade**
In hopes of simplifying the PR/merge process a bit, I combined the feature/Sequence* PRs into this one PR.  Not such a big deal here, but in the C# PR of the same name, the code was very interdependent across the different tools.  

The other PRs that this one collectively contains can be deleted.

### CODE REVIEW

**Comment by mattstahl00** [comment]
I'm getting the following error when testing the Sequence Pattern match data function with the 'dev' branch of Publisher:

PublisherCore.SequencePatternMatchDataFunction data function

Unknown service PublisherCore.SequencePatternMatchDataFunction

   at PublisherCore.CSharpExecutor.Run(DataFxnRequest request, DataFunctionInvocation invocation, CancellationToken token) in D:\dev\csharp\Dev\Publisher\PublisherCore\src\df\CSharpExecutor.cs:line 87
   at ChemistryService.DataFxnExecutorBase.<ExecuteFunctionCore>d__1.MoveNext() in D:\dev\csharp\Dev\Publisher\ChemistryService\src\DataFxnExecutorBase.cs:line 120

**Comment by KirkD-Glysade** [comment]
> I'm getting the following error when testing the Sequence Pattern match data function with the 'dev' branch of Publisher:
> 
> PublisherCore.SequencePatternMatchDataFunction data function
> 
> Unknown service PublisherCore.SequencePatternMatchDataFunction
> 
> at PublisherCore.CSharpExecutor.Run(DataFxnRequest request, DataFunctionInvocation invocation, CancellationToken token) in D:\dev\csharp\Dev\Publisher\PublisherCore\src\df\CSharpExecutor.cs:line 87 at ChemistryService.DataFxnExecutorBase.d__1.MoveNext() in D:\dev\csharp\Dev\Publisher\ChemistryService\src\DataFxnExecutorBase.cs:line 120


I'm looking into it now.  This one may be old enough that it needs the master branch merged in to get everything else up to date.

**Comment by KirkD-Glysade** [comment]
I merged in master and got a few extra commits.

This PR is linked to another in Publisher on BitBucket, but that one should already be merged into dev.

* SequencePatternMatchDataFunction should have been deleted, or renamed SequenceLiabilitySearchDataFunction in this repo.  It should also be expanded from the original 2 sequence searches to 8.
* SequenceLiabilitySearchDataFunction is part of the PR on the Publisher repo, and looks like it is there - https://bitbucket.org/glysadelic/publisher/pull-requests/9

**Comment by KirkD-Glysade** [comment]
There was an error in the -servicename for the DataFunction which I changed here. and made a small modification to CSharpExecutor.cs in Publisher - I'll create that PR next called hotfix/SequenceTools_230725.  Unit tests for all 4 sequence tools pass in Publisher with this change and the one in Publisher.

**Comment by mattstahl00** [comment]
Please also swap the column order on the motif search.

**Comment by KirkD-Glysade** [comment]
> The min charts version for Sequence Liabilities will need to be 4.4.0.0 since the change was just merged into dev. Are the min charts versions for the other data fxns still correct? Did you test them from the FE with a release > 4.3.0.6?

I tested all of these with version 4.4.0.0 from yesterday (17 October 2023) and all tests passed.

**Comment by mattstahl00** [comment]
You'd need to test with CC 4.3.0.19 to know whether the minChartsVersion is correct.  Any data fxns that don't work in that version should get a minChartsVersion of 4.4.0.0.  Once those defns go into master, they'll be included in the next 4.3 build.

**Comment by KirkD-Glysade** [comment]
I tested in CC 4.3.0.19 and <sigh> all failed with an unknown service error.  Looking at the history of CSharpExecutor.cs and it was merged into dev on 9 Sept but there may have been merge conflicts later.

I tested all of these on a compiled version of Publisher (CC 4.4.0.0) and they all worked through FE as well as passed unit tests.  I'll change all minChartsVersion to 4.4.0.0

**Comment by KirkD-Glysade** [comment]
* Annotated Sequence Liabilities moved to front - done.
* Rename output column to "Annotated Liabilities" - done.
* Rename data function to "Sequence Liabilities"  -  I suggest Antibody Sequence Liabilities to indicate the specific intent.  This created a disconnect with the name of the class in C#, so I renamed that to "AntibodySequenceLiabilitiesDataFunction" and refactored as needed.
* Move annotated motif column to front - done.

* Manually tested all DFs in this PR in a compiled version of Publisher v4.4.0.0 (fresh pull and clean/restore/rebuild today)
   *  Found border case bug and created correction
* All C# unit tests pass

**Pull request merged**
